echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'
[global]
ioengine=psync
size=100g
direct=1
thread
group_reporting
name=mytest
iodepth=1
runtime=120

[work1]
filename=/dev/sdb
bs=4K
rw=randwrite
numjobs=30
[work2]
filename=/dev/sdb
bs=4K
rw=randread
numjobs=30
[work3]
filename=/dev/sdb
bs=512K
rw=write
numjobs=30
[work3]
filename=/dev/sdb
bs=512K
rw=read
numjobs=30